### PR TITLE
Mask HPKP and HSTS headers from remote server

### PR DESCRIPTION
**Pull request by ajhaydock**
Potential fix for #3 but probably a decent idea anyway

### CODE REVIEW

**Comment by ajhaydock** [comment]
Ugh... one day I will work out how to use git branches properly, but clearly today is not that day. Think I was working in master for the last PR so it seems to reference all of those commits here too. Let me know if that will cause problems when merging and I'll fix it.

**Comment by sainslie** [comment]
Thank you! @nginx isn't familiar as I use @apache but I'm glad that this potential fix for #3 is being addressed. I'm curious about @alecmuffett thoughts about this too.

**Comment by alecmuffett** [comment]
Good add, Alex, but could you please check out existing lines 86-96 and integrate into those?
Maybe these should be default-on? What do you think?

**Comment by alecmuffett** [comment]
@sainslie Well, EOTK is clearly a glorified MITM, and Tor/Onion obviates some of the need (and indeed value, since TBB does not support HSTS) - so nuking it seems fair enough.

**Comment by alecmuffett** [comment]
aside: if you are working on templates and want to check for typos/whatever, or just see what it there, try:

```
$ ./lib.d/lint.pl templates.d/*
2 CERT_PREFIX
9 DNS_DOMAIN
1 DNS_DOMAIN_RE
1 HEADER_CSP_SUPPRESS
3 I <- *unknown*
9 IS_SOFTMAP
4 LOG_DIR
8 NEW_ONION <- *unknown*
1 NGINX_HELLO_ONION
...
```

**Comment by ajhaydock** [comment]
Ah I hadn't noticed you already had some code in there to suppress the HSTS header. I'll rework this commit to integrate the HPKP header suppression into the same area.

As for whether it should be on by default, I would definitely mask the HPKP header by default, and I suppose if TBB doesn't support HSTS then there's no harm in getting rid of that either.

**Comment by alecmuffett** [comment]
fixed - take a look, close this if it works for you.

**Comment by ajhaydock** [comment]
Yep. This seems like it works for me.

**Pull request closed without merging**
