### PR TITLE
HTTP Secure

### PR DESCRIPTION
**Pull request by sainslie**
I added support for it. It's supported @nginx repositories and it's beneficial to capitalize on its properties in addition to detached digital signatures. I also added support to [gnupg](https://packages.debian.org/stable/admin/gnupg) too. [gnupg-curl](https://packages.debian.org/stable/admin/gnupg-curl) is a prerequisite to using it @ubuntu.

### CODE REVIEW

**Comment by ajhaydock** [comment]
Nice. I didn't know about `hkps://`

**Comment by alecmuffett** [comment]
Hi @sainslie - quick question, since I am still getting to grips with GitHub: have you rebased/merged recently?

**Comment by alecmuffett** [comment]
looks like it, to judge by your final commit?

**Comment by alecmuffett** [comment]
hm - it breaks Raspbian:

``` 
13:31:17 rig0:eotk.d $ gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys  B0F4253373F8F6F510D42178520A9993A1C052F8
gpg: requesting key A1C052F8 from hkps server keyserver.ubuntu.com
gpgkeys: HTTP fetch error 1: unsupported protocol
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
```

**Comment by sainslie** [comment]
@alecmuffett I did do that though it's not a problem. It appears as though it's duplicated but I hadn't realized that it hadn't been up-to-date prior to adding support so I had to do it again and resign it. @ajhaydock [gnupg](https://packages.debian.org/stable/admin/gnupg) supports it but it's not the default option using @ubuntu though I suggest that it should use it. It's great! @alecmuffett [gnupg-curl](https://packages.debian.org/stable/admin/gnupg-curl) is required to use it. @raspberrypi does support it. It's just a matter of installing [gnupg-curl](https://packages.debian.org/stable/admin/gnupg-curl) from its repositories.

**Comment by ajhaydock** [comment]
For what it's worth, the newer `gnupg2` package also seems to support HKPS, but without any additional dependencies.

**Pull request closed without merging**
