### PR TITLE
Add Custom CSP support

### PR DESCRIPTION
**Pull request by larsveelaert**

### CODE REVIEW

**Comment by alecmuffett** [comment]
This is a great idea! But I don't like the face that it's implemented as a nested setting - I try to avoid those where possible - and also that the setting is missing from the `lint` and `do-configure` scripts; are you willing to revisit those latter, at least, or shall I just hack an equivalent in?

**Comment by alecmuffett** [comment]
Specifically it seems a bit illogical to "suppress" the header AND use a custom header.

I would rather see a separate test being make in the %%ELSE ... %%ENDIF of the same block, even if it results in a little code duplication of `proxy_hide_header`. 

What do you think?

**Comment by larsveelaert** [comment]
I wrote this code quite quick. There is some extra code missing in other places.
In general my config options like "set force_https 0" don't seem to work.
When I look in the log-file the option is still the default.

When manually changing the defaults and adding my new options, the csp-header did not appear.
Manually adding more_set_headers to the end of the nginx.conf file after generation by the conf-command.

Thank you for the notes on indentation.

I think in general adding the csp header to control the fingerprint of the application and break the application deliberatly when something is changed and could deanonymise the user.

**Comment by alecmuffett** [comment]
> I think in general adding the csp header to control the fingerprint of the application and break the application deliberatly when something is changed and could deanonymise the user.

Interesting. 

How do you see that working? 

After all (for example) the EOTK instance at the New York Times is run by the same people who run the New York Times website, so preservation of anonymity is not really relevant to their model.

**Comment by alecmuffett** [comment]
So... your goal is to manually set the CSP headers in responses for the Onion for your website, to something different from what-they-would-be-by-onionifying-the-original-header, in order to make tighter restrictions upon what the Onionified website's DOM can/will load?

**Comment by larsveelaert** [comment]
Yes, exactly.

**Comment by alecmuffett** [comment]
interesting.  do you want to work on a revised pull-request?

**Comment by larsveelaert** [comment]
Yes I will, I am running a test-version now, so if that works I will revise the code

**Comment by larsveelaert** [comment]
@alecmuffett 
I'm having troubles with the config file.
The force_https setting does not seem to be enforced.

I have;
```
set force_https 0
set project test
hardmap <onion-addr>.onion testing.com
```

Do you know what I'm doing wrong?
To cleanly implement the csp-functionality I want it to read from the conf ofcourse.

**Comment by alecmuffett** [comment]
I can't reproduce the issue, let me share what I did:

- make sure you are editing the `.conf` file NOT the `.tconf` file
- make sure you do `set force_https 0` in the `.conf` file
- make sure to regenerate the config using `eotk config foo.conf`
- check the resulting `nginx.conf` file; you should find strings like:
  - `FORCE_HTTPS is not in use, cleartext data may traverse the internet`
  - `listen unix:/path/eotk/projects.d/foo.d/xxxxxxxxxxxxxxxx.onion.d/port-80.sock;`

This will confirm that FORCE_HTTPS is disabled.

**Comment by alecmuffett** [comment]
This is what it looks like in the `nginx.conf` when FORCE_HTTPS is disabled:

screen shot 2018-04-10 at 23 42 17

**Comment by alecmuffett** [comment]
closing because stale

**Pull request closed without merging**
